"""Generate single-row PERCENTAGE figures for the consolidated feature-importance
section of the thesis (ablation + PFI).

Reads the canonical diagnostics CSVs (regenerated by rerun_xai_canonical.py) and
produces, for each method, a 1x3 panel of relative degradation (% of baseline) per
task. Replaces the previous two-row (absolute + relative) ablation figure and the
absolute-valued PFI figure.

Outputs:
  thesis/figures/feature_ablation.png
  thesis/figures/pfi_results.png
"""
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap, Normalize

# ---- CONDOR visual identity ----
CONDOR_DARKRED = "#6E1423"
CONDOR_RED     = "#A4243B"
CONDOR_INK     = "#1A1A1A"
CONDOR_GRAY    = "#9E9E9E"
CONDOR_CREAM   = "#F2E8E5"
SAVE_DPI = 200
CMAP_SEQ = LinearSegmentedColormap.from_list(
    "condor_seq", [CONDOR_CREAM, "#C97B86", CONDOR_RED, CONDOR_DARKRED, "#3D0A14"])

mpl.rcParams.update({
    "figure.facecolor": "white", "axes.facecolor": "white",
    "font.family": "serif", "font.size": 13,
    "axes.labelsize": 13, "axes.labelcolor": CONDOR_INK,
    "axes.edgecolor": CONDOR_INK, "axes.linewidth": 0.9, "axes.titlesize": 14,
    "axes.titleweight": "bold",
    "xtick.color": CONDOR_INK, "ytick.color": CONDOR_INK,
    "xtick.labelsize": 12, "ytick.labelsize": 12,
    "legend.fontsize": 12,
    "grid.color": CONDOR_GRAY, "grid.alpha": 0.25, "grid.linewidth": 0.6,
})

HERE = Path(__file__).resolve().parent
DIAG = HERE / "pipeline_artifacts" / "diagnostics"
FIGS = HERE.parent / "thesis" / "figures"
FIGS.mkdir(parents=True, exist_ok=True)

TASK_ORDER = ["particle", "angle", "energy"]
TASK_TITLE = {
    "particle": "Gamma-Hadron Discrimination",
    "angle":    "Zenith Angle Reconstruction",
    "energy":   "Energy Estimation",
}
XLAB = "Relative degradation (\\%)" if mpl.rcParams["text.usetex"] else "Relative degradation (%)"


def _barh_panel(ax, names, pct, title):
    """Horizontal bars sorted by magnitude, colored by magnitude (darker = larger)."""
    order = np.argsort(pct)  # ascending -> largest on top after barh
    names = [names[i] for i in order]
    pct = np.asarray(pct)[order]
    norm = Normalize(vmin=0, vmax=max(pct.max(), 1e-9))
    colors = CMAP_SEQ(norm(pct))
    ax.barh(names, pct, color=colors, edgecolor=CONDOR_INK, linewidth=0.6)
    for y, v in enumerate(pct):
        ax.text(v + pct.max() * 0.01, y, f"{v:.1f}%", va="center", ha="left",
                fontsize=8.5, color=CONDOR_INK)
    ax.set_title(title, fontweight="bold")
    ax.set_xlabel("Relative degradation (%)")
    ax.set_xlim(0, pct.max() * 1.18)
    ax.grid(True, axis="x")


def make_ablation_figure():
    df = pd.read_csv(DIAG / "feature_ablation_results.csv")
    fig, axes = plt.subplots(1, 3, figsize=(18, 5.2), constrained_layout=True)
    for ax, task in zip(axes, TASK_ORDER):
        sub = df[df["task"] == task]
        names = sub["feature"].tolist()
        pct = np.abs(sub["pct_change"].to_numpy())  # particle pct is negative
        _barh_panel(ax, names, pct, TASK_TITLE[task])
    fig.suptitle("Feature ablation — relative degradation when each feature "
                 "is replaced by its training-set median",
                 fontweight="bold", fontsize=13)
    out = FIGS / "feature_ablation.png"
    fig.savefig(out, dpi=SAVE_DPI, bbox_inches="tight")
    print("Saved:", out)
    # report for text reconciliation
    for task in TASK_ORDER:
        sub = df[df["task"] == task].assign(pct=lambda d: d["pct_change"].abs())
        top = sub.sort_values("pct", ascending=False).head(3)
        print(f"  ablation/{task}:", list(zip(top["feature"], top["pct"].round(1))))


def make_pfi_figure():
    df = pd.read_csv(DIAG / "pfi_all_heads_sequence_only.csv")
    df["feature"] = df["feature"].str.replace("sequence::", "", regex=False)
    df["pct"] = 100.0 * df["importance_delta"] / df["baseline"]
    fig, axes = plt.subplots(1, 3, figsize=(18, 5.2), constrained_layout=True)
    for ax, task in zip(axes, TASK_ORDER):
        sub = df[df["task"] == task]
        _barh_panel(ax, sub["feature"].tolist(), sub["pct"].to_numpy(),
                    TASK_TITLE[task])
    fig.suptitle("Permutation feature importance — relative degradation when "
                 "each feature is permuted across events",
                 fontweight="bold", fontsize=13)
    out = FIGS / "pfi_results.png"
    fig.savefig(out, dpi=SAVE_DPI, bbox_inches="tight")
    print("Saved:", out)
    for task in TASK_ORDER:
        sub = df[df["task"] == task]
        top = sub.sort_values("pct", ascending=False).head(3)
        print(f"  pfi/{task}:", list(zip(top["feature"], top["pct"].round(1))))


if __name__ == "__main__":
    make_ablation_figure()
    make_pfi_figure()
